{
 "title": "Workflow Furious Ducks",
 "refresh": "30s",
 "panels": [
  {
   "title": "Load Jenkins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"jenkins\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU containers TipTop",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"(front|api).*\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "Utilisation mémoire",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container=~\"(front|api).*\"}) by (container)"
    }
   ]
  }
 ]
}